#REPETITIVAS ITERACION QUE INPRIME CUALQUIER CADENA ESCRITA POR TECLADO
import os
nombre=""

#ARGUMENTO
#ASIGNACION DE VALORES
nombre=os.sys.argv[1]

#PROCESSING DE LA ESTRUCTURA "ITERACION"
for x in nombre:
    print(x)
#fin_iterar
print("FIN DEL BUCLE")
