#REPETITIVAS ITERACION QUE CALCULA CUALQUIER CADENA + AGREGADO LA PALABRA PROGRAMACION
import os

#ARGUMENTO
#ASIGNACION DE VALORES
cadena=os.sys.argv[1]

#PROCESSING DE LA ESTRUCTURA "ITERACION"
for y in cadena:
  print(y,"PROGRAMACION")
#fin_iterar
print("FIN DEL BUCLE")
