#REPETITIVAS ITERACION RANGO QUE INPRIME LOS PRIMEROS NUMEROS MULTIPLOS SEGUN EL NUMERO INGRESADO POR TECLADO
#SI EL NUMERO INGRESADO POR TECLADO ES MULTIPLO DE 4 ENTONSES TE INPRIME LOS PRIMEROS NUMEROS MULTIPLOS DE 4
#SI EL NUMERO INGRESADO POR TECLADO ES MULTIPLO DE 5 ENTONSES TE IMPRIME LOS PRIMEROS NUMEROS MULTIPLOS DE 5
import os

#ARGUMENTOS
#ASIGNACION DE VALORES
valor= int(os.sys.argv[1])

#PROCESSING DE LA ESTRUCTURA "ITERACION RANGO
for x in range(1,15):
    print(x*valor)
#fin_iterar
print("FIN DEL BUCLE")
