#REPETITIVAS ITERACION RANGO QUE MUESTRA N PALABRAS "PROGRAMACIO", N SE ESCRIBE POR TECLADO
import os
x=0

#ARGUMENTOS
#ASIGNACION DE VALORES
x=int(os.sys.argv[1])

#PROCESSING DE LA ESTRUCTURA "ITERACION RANGO"
for x in range(x):
    print("PROGRAMACION",x)
#fin_iterar
print("FIN DEL BUCLE")
