#REPETITIVAS ITERACION RANGO QUE CALCULA CUALQUER CADENA CON SU RESPECTIVO NUMERO DEL 0 AL 15
import os

#ARGUMENTO
#ASIGNACION DE VALORES
cadena=os.sys.argv[1]

#PROCESSING DE LA ESTRUCTURA "INTERACION RANGO"
for x in range(0,16):
    print(cadena,"",x)
#fin_iterar
print("FIN DEL BUCLE")
